In [2]:
# load artifacts (from disk)
import json, pandas as pd
from chessrl.eval.helpers import (
    vi_move_from_policy_map, vi_move_from_values,
    mcts_move_from_instance,
)
from chessrl.eval.evaluator import evaluate
from chessrl.algorithms.mcts.mcts import MCTS
from chessrl.eval.helpers import optimal_moves_syzygy

# load artifacts (from disk)
from chessrl.utils.io import load_vf_parquet, load_policy_jsonl
from chessrl import RandomDefender

2025-09-03 13:23:50,492 - INFO - Loading config file...

In [3]:
TB_PATH = "../../../tablebase/krk/"

# dtm oracle
dtz_oracle = pd.read_csv(TB_PATH + "krk_full.csv").set_index("fen")["dtz"].to_dict()
dtm_oracle = lambda fen: abs(int(dtz_oracle[fen]))

# optimal moves source
opt_moves   = optimal_moves_syzygy(TB_PATH)

# evaluate (same function for all)
test_fens = [ "8/8/8/8/8/8/k7/2K4R w - - 0 1", "8/8/8/8/8/8/k7/2K2R2 w - - 0 1", "8/8/8/8/8/8/k7/2K4R w - - 0 1" ]

# MCTS

In [4]:

mcts = MCTS(seconds=6.0, iterations=5_000, use_env_in_rollout=True,
            defender=RandomDefender(0), absorb_black_reply=True)
move_fn = mcts_move_from_instance(mcts, "seconds")

In [5]:
test_fens = ["k7/2R5/1K6/8/8/8/8/8 w - - 0 1"]

df_mcts = evaluate(
    move_fn=move_fn,
    defender=RandomDefender(0),
    fens=test_fens,
    dtm_oracle=dtm_oracle,
    optimal_moves=opt_moves,
    budget=6.0
)

df_mcts

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,k7/2R5/1K6/8/8/8/8/8 w - - 0 1,1,1,0,1,3520.27976,1.0,1,6.0

# Value Iteration

## from policy

In [4]:
from chessrl.env import SyzygyDefender
defender = SyzygyDefender(TB_PATH)

In [18]:

# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

# Sample 2 positions for each unique DTM value
test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]
test_fens

/tmp/ipykernel_9456/4281499682.py:8: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

0       8/8/k1K5/8/8/8/8/7R w - - 0 1
1      5k2/8/5K2/8/8/8/7R/8 w - - 0 1
2      4R3/8/8/8/8/7K/8/6k1 w - - 0 1
3     8/8/8/3R4/5K2/8/8/4k3 w - - 0 1
4      k2K4/8/5R2/8/8/8/8/8 w - - 0 1
5      8/8/8/6R1/8/k7/3K4/8 w - - 0 1
6      8/8/8/8/8/4K3/4R3/k7 w - - 0 1
7      R3K1k1/8/8/8/8/8/8/8 w - - 0 1
8     8/3R4/8/8/8/4K3/8/1k6 w - - 0 1
9      8/8/6K1/6R1/8/8/7k/8 w - - 0 1
10     3k1K2/8/8/7R/8/8/8/8 w - - 0 1
11     8/8/7k/8/5K2/8/3R4/8 w - - 0 1
12      8/8/7K/4R3/8/7k/8/8 w - - 0 1
13      6R1/8/7k/8/8/7K/8/8 w - - 0 1
14    8/8/5R2/8/4K3/8/4k3/8 w - - 0 1
15    8/8/1k6/8/2K5/8/6R1/8 w - - 0 1
16     5K2/5R2/7k/8/8/8/8/8 w - - 0 1
17     8/8/8/1K6/8/6R1/7k/8 w - - 0 1
18    8/3R1K2/8/8/8/8/8/6k1 w - - 0 1
19     8/7k/8/8/8/1K6/3R4/8 w - - 0 1
20    8/2k5/8/8/8/5R2/1K6/8 w - - 0 1
21     8/8/8/1K6/7k/8/3R4/8 w - - 0 1
22       K7/R7/8/8/8/8/7k/8 w - - 0 1
23      8/1k6/8/R7/7K/8/8/8 w - - 0 1
24      8/8/2k5/7K/7R/8/8/8 w - - 0 1
25    8/1R6/4k3/8/8/1K6/8/8 w - - 0 1
26     4K3/8/8/8/8/3k4/8/7R w - - 0 1
27     K7/8/8/8/8/8/2k5/5R2 w - - 0 1
28      KR6/8/8/8/4k3/8/8/8 w - - 0 1
29    2R5/3k4/8/8/8/8/1K6/8 w - - 0 1
30     8/7K/8/8/8/2k5/1R6/8 w - - 0 1
31     6R1/8/5k2/8/8/8/8/K7 w - - 0 1
Name: fen, dtype: object

In [ ]:
# choose version to test
policy_map = load_policy_jsonl("../../../artifacts/policies/vi_probabilistic_krk_greedy.jsonl")

vi_agent = vi_move_from_policy_map(policy_map)
df_vi     = evaluate(vi_agent, defender, test_fens, dtm_oracle, optimal_moves=opt_moves)
df_vi

## from value function

In [7]:
# V = load_vf_parquet("../../../artifacts/values/vi_probabilistic_krk_SyzygyDefender_greedy_intermediate_16.parquet")
V = load_vf_parquet("../../../artifacts/values/vi_krk_values.parquet")

df = pd.DataFrame.from_dict(V, orient='index', columns=['value']).reset_index().rename(columns={'index': 'fen'})

df

                                   fen  value
0        8/8/8/8/8/8/R7/K1k5 w - - 0 1  -15.0
1       8/8/8/8/8/8/1R6/K1k5 w - - 0 1  -15.0
2       8/8/8/8/8/8/3R4/K1k5 w - - 0 1  -15.0
3       8/8/8/8/8/8/4R3/K1k5 w - - 0 1  -15.0
4       8/8/8/8/8/8/5R2/K1k5 w - - 0 1  -15.0
...                                ...    ...
182671    3k3K/8/8/8/8/8/8/8 b - - 0 1    0.0
182672    4k2K/8/8/8/8/8/8/8 w - - 0 1    0.0
182673    4k2K/8/8/8/8/8/8/8 b - - 0 1    0.0
182674    5k1K/8/8/8/8/8/8/8 w - - 0 1    0.0
182675    5k1K/8/8/8/8/8/8/8 b - - 0 1    0.0

[182676 rows x 2 columns]

In [24]:

vi_v_agent = vi_move_from_values(V, TB_PATH)

df_vi_v   = evaluate(vi_v_agent, RandomDefender(2), test_fens, dtm_oracle, optimal_moves=opt_moves)

df_vi_v

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,47.387289,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,1,1,0.0,1,30.506807,1.000000,1,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,3,3,0.0,1,25.972083,1.000000,2,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,3,3,0.0,1,47.745175,1.000000,2,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,7,5,2.0,1,23.247177,0.750000,4,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,5,5,0.0,1,32.940232,1.000000,3,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,6,7,NaN,0,31.547489,0.000000,3,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,4,7,NaN,0,23.585418,0.500000,2,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,6,9,NaN,0,46.563800,0.000000,3,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,6,9,NaN,0,34.368210,0.000000,3,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,6,11,NaN,0,27.642000,0.000000,3,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,7,11,0.0,1,31.209739,0.500000,4,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,4,13,NaN,0,33.027741,0.500000,2,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,2,13,NaN,0,29.713323,0.000000,1,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,2,15,NaN,0,34.399080,0.000000,1,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,5,15,0.0,1,36.164867,1.000000,3,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,4,17,NaN,0,24.931797,0.000000,2,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,2,17,NaN,0,27.935211,0.000000,1,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,4,19,NaN,0,37.039626,0.000000,2,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,4,19,NaN,0,191.409554,0.500000,2,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,12,21,NaN,0,34.098165,0.166667,6,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,6,21,NaN,0,32.506082,0.333333,3,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,6,23,NaN,0,31.643368,0.000000,3,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,14,23,NaN,0,28.060305,0.000000,7,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,300,25,NaN,0,25.894417,0.013333,150,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,12,25,NaN,0,42.434723,0.000000,6,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,4,27,NaN,0,40.224955,0.000000,2,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,4,27,NaN,0,37.920564,0.000000,2,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,12,29,NaN,0,37.538732,0.000000,6,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,10,29,NaN,0,38.595894,0.200000,5,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,6,31,NaN,0,172.122855,0.000000,3,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,6,31,NaN,0,43.807338,0.000000,3,None

## value function vs random defender

In [3]:
from chessrl import RandomDefender, SyzygyDefender


# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

/tmp/ipykernel_9021/201573114.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

In [ ]:

V = load_vf_parquet("../../../artifacts/values/vi_krk_values.parquet")

vi_v_agent = vi_move_from_values(V, TB_PATH)

df_vi_v   = evaluate(vi_v_agent, RandomDefender(3), test_fens, dtm_oracle, optimal_moves=opt_moves)
df_vi_v

# TD methods

### Q-learning

In [58]:
# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_train.csv")
test_df = test_df[test_df['dtz'].isin([3])]
test_df
test_fens = test_df['fen']

In [59]:
# Load Q-Learning policy
qlearning_policy = load_policy_jsonl("../../../artifacts/policies/TD_QLearning_krk_SyzygyDefender_greedy.jsonl")
qlearning_agent = vi_move_from_policy_map(qlearning_policy)

In [63]:
df_q = evaluate(qlearning_agent, SyzygyDefender(TB_PATH), test_fens[:50], dtm_oracle, optimal_moves=opt_moves)

In [61]:
df_q

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/R7/8/8/K7/8/1k6 w - - 0 1,300,3,None,0,0.003158,0.000000,150,None
1,8/8/8/8/4R3/8/7K/5k2 w - - 0 1,300,3,None,0,0.002880,0.493333,150,None
2,5k2/8/4K3/8/8/8/R7/8 w - - 0 1,300,3,None,0,0.002887,0.000000,150,None
3,8/8/8/8/8/2KR4/k7/8 w - - 0 1,300,3,None,0,0.002785,0.493333,150,None
4,6k1/8/6K1/8/8/6R1/8/8 w - - 0 1,300,3,None,0,0.003162,0.486667,150,None
5,3k4/8/4K3/8/8/2R5/8/8 w - - 0 1,300,3,None,0,0.002774,0.006667,150,None
6,8/8/8/8/8/8/4RK1k/8 w - - 0 1,300,3,None,0,0.002784,0.000000,150,None
7,8/8/k7/2K3R1/8/8/8/8 w - - 0 1,300,3,None,0,0.002955,0.486667,150,None
8,1k6/8/K1R5/8/8/8/8/8 w - - 0 1,300,3,None,0,0.002981,0.013333,150,None
9,8/8/8/8/8/8/k1K5/5R2 w - - 0 1,300,3,None,0,0.003057,0.000000,150,None

### Sarsa

In [48]:
sarsa_policy = load_policy_jsonl("../../../artifacts/policies/TD_SARSA_krk_SyzygyDefender_greedy.jsonl")
sarsa_agent = vi_move_from_policy_map(sarsa_policy)

In [51]:
df_sarsa = evaluate(sarsa_agent, RandomDefender(0), test_fens[:2], dtm_oracle, optimal_moves=opt_moves)

In [52]:
df_sarsa

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,0.004038,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,168,1,NaN,0,0.006469,0.071429,84,None

In [8]:
df_sarsa_random = evaluate(sarsa_agent, RandomDefender(0), test_fens, dtm_oracle, optimal_moves=opt_moves)
df_sarsa_random

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,0.002121,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,114,1,NaN,0,0.002735,0.087719,57,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,30,3,NaN,0,0.002639,0.200000,15,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,174,3,NaN,0,0.002944,0.091954,87,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,150,5,NaN,0,0.002736,0.040000,75,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,124,5,NaN,0,0.002907,0.096774,62,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,20,7,NaN,0,0.002752,0.100000,10,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,64,7,NaN,0,0.002498,0.093750,32,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,300,9,NaN,0,0.003952,0.140000,150,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,28,9,NaN,0,0.002314,0.357143,14,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,28,11,NaN,0,0.002290,0.214286,14,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,300,11,NaN,0,0.002467,0.073333,150,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,138,13,NaN,0,0.002338,0.101449,69,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,8,13,NaN,0,0.002527,0.000000,4,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,16,15,NaN,0,0.002431,0.125000,8,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,272,15,NaN,0,0.002427,0.117647,136,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,70,17,NaN,0,0.002635,0.171429,35,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,6,17,NaN,0,0.002207,0.000000,3,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,162,19,NaN,0,0.002733,0.209877,81,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,176,19,NaN,0,0.002586,0.045455,88,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,300,21,NaN,0,0.002913,0.153333,150,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,300,21,NaN,0,0.003105,0.106667,150,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,28,23,NaN,0,0.002911,0.214286,14,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,242,23,NaN,0,0.003205,0.157025,121,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,70,25,NaN,0,0.003394,0.142857,35,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,160,25,NaN,0,0.003171,0.125000,80,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,136,27,NaN,0,0.003130,0.117647,68,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,6,27,NaN,0,0.002710,0.000000,3,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,116,29,NaN,0,0.003103,0.120690,58,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,26,29,NaN,0,0.002886,0.307692,13,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,174,31,NaN,0,0.002933,0.126437,87,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,300,31,NaN,0,0.002935,0.066667,150,None

# Actor-Critic